In [2]:
import pandas as pd
import numpy as np

dict = {'Republic of Korea':'South Korea',
       'United States of America':'United States',
       'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
       'China, Hong Kong Special Administrative Region':'Hong Kong'}

In [3]:
energy = pd.read_excel('Energy Indicators.xls',
                       skiprows=17, skipfooter=38,usecols=[2,3,4,5],
                      names=['Country','Energy Supply','Energy Supply per Capita','% Renewable'],
                      )
#energy.rename(columns={0:'Country',
#                       'Renewable Electricity Production':'% Renewable'},inplace=True)

energy['Country']=energy['Country'].str.replace(r'\(.*\)','') #replace ()
energy['Country']=energy['Country'].str.replace('\d+','') # replace digits

for non in energy:
    energy[non] = energy[non].replace('...','np.NaN')
#energy['Energy Supply'] *=1000000

energy['Country']= energy['Country'].map(dict)

energy

            Country Energy Supply Energy Supply per Capita  % Renewable
0               NaN           321                       10    78.669280
1               NaN           102                       35   100.000000
2               NaN          1959                       51     0.551010
3               NaN        np.NaN                   np.NaN     0.641026
4               NaN             9                      121    88.695650
5               NaN           642                       27    70.909090
6               NaN             2                      136     0.000000
7               NaN             8                       84     0.000000
8               NaN          3378                       79    24.064520
9               NaN           143                       48    28.236060
10              NaN            12                      120    14.870690
11              NaN          5386                      231    11.810810
12              NaN          1391                      164    72.452820
13              NaN           567                       60     6.384345
14              NaN            45                      118     0.000000
15              NaN           574                      425     0.000000
16              NaN          1625                       10     1.966329
17              NaN            19                       69     0.000000
18              NaN          1142                      120     0.463389
19              NaN          2338                      210     9.959739
20              NaN            13                       39    64.690030
21              NaN           170                       16     0.000000
22              NaN             6                       88     0.000000
23              NaN            63                       83   100.000000
24              NaN           336                       32    31.477120
25              NaN             5                      213     0.000000
26              NaN           266                       70    41.464670
27              NaN            86                       39     0.131406
28              NaN         12149                       59    69.648030
29              NaN             2                       85     0.000000
..              ...           ...                      ...          ...
197             NaN          1113                      136    57.745480
198             NaN           542                       28    11.568270
199             NaN           106                       13    99.742920
200             NaN          5336                       79     4.305189
201             NaN           117                       56    26.140470
202             NaN             7                        6     0.000000
203             NaN           134                       19    80.180180
204             NaN             3                       28     0.000000
205             NaN           824                      611     0.000000
206             NaN           430                       39     3.492547
207             NaN          4897                       64    28.536690
208             NaN          1102                      210     0.000000
209             NaN             3                       85     0.000000
210             NaN        np.NaN                   np.NaN     0.000000
211             NaN           452                       12    68.018180
212             NaN          4844                      107     8.067312
213             NaN          2710                      300     0.000000
214  United Kingdom          7920                      124    10.600470
215             NaN           994                       20    31.072840
216   United States         90838                      286    11.570980
217             NaN        np.NaN                   np.NaN     0.000000
218             NaN           196                       58    71.605040
219             NaN          1798                       62    21.328410
220             NaN             3                       10    14.705880
221             NaN          2871                       95    67.834520
222             NaN          2554                       28    45.321520
223             NaN             0                       26     0.000000
224             NaN           344                       13     0.000000
225             NaN           400                       26    99.714670
226             NaN           480                       32    52.536120

[227 rows x 4 columns]

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Australia,14,8831,8725,90765,15606,10.28,107,5386,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [164]:
    #energy
    energy = pd.read_excel('Energy Indicators.xls',
                           skiprows=17, skipfooter=38,usecols=[2,3,4,5],
                          names=['Country','Energy Supply','Energy Supply per Capita','% Renewable'],
                          )
    #energy.rename(columns={0:'Country',
    #                       'Renewable Electricity Production':'% Renewable'},inplace=True)
    
    energy.dropna()
    
    energy['Country']=energy['Country'].str.replace(r'\(.*\)','') #replace ()
    energy['Country']=energy['Country'].str.replace('\d+','') # replace digits
    energy['Country']=energy['Country'].str.strip()
    for non in energy:
        energy[non] = energy[non].replace('...','np.NaN')
    #energy['Energy Supply'] *=1000000

    energy['Country']= energy['Country'].replace({'Republic of Korea':'South Korea',
                                                  'United States of America':'United States',
                                                 'United Kingdom of Great Britain and Northern Ireland':'United Kingdom',
                                                 'China, Hong Kong Special Administrative Region':'Hong Kong'})

    
    #GDP
    GDP = pd.read_csv('world_bank.csv',skiprows=4)
    GDP['Country Name']=GDP['Country Name'].replace({"Korea, Rep.": "South Korea", 
                                                     "Iran, Islamic Rep.": "Iran",
                                                     "Hong Kong SAR, China": "Hong Kong"})
    GDP = GDP.rename(columns={'Country Name':'Country'})
    GDP = GDP.drop(GDP.iloc[:,1:50],axis=1)
    #GDP = GDP.filter(['Country','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015'])
    
    #ScimEn
    ScimEn = pd.read_excel('scimagojr-3.xlsx')
    
    
    df_SE = pd.merge(ScimEn, energy, how='inner',left_on='Country',right_on='Country')
    df_SEG = pd.merge(df_SE, GDP, how='inner',left_on='Country',right_on='Country').set_index('Country')
    df=df_SEG[:15]
    df
    
#     df_SE_outer = pd.merge(ScimEn, energy, how='outer',left_on='Country',right_on='Country')
#     df_SEG_outer = pd.merge(df_SE_outer, GDP, how='outer',left_on='Country',right_on='Country').set_index('Country')
#     #outer = len(pd.concat([ScimEn['Country'],energy['Country'],GDP['Country']]).unique())
#     len(df_SEG_outer)
#     dif=len(df_SEG_outer)-len(df_SEG)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,127191,93,19.754910,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12
United States,2,96661,94747,792274,265436,8.20,230,90838,286,11.570980,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
Japan,3,30504,30287,223024,61554,7.31,134,18984,149,10.232820,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12
United Kingdom,4,20944,20357,206091,37874,9.84,139,7920,124,10.600470,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12
Russian Federation,5,18534,18301,34266,12422,1.85,57,30709,214,17.288680,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12
Canada,6,17899,17620,215003,40930,12.01,149,10431,296,61.945430,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12
Germany,7,17027,16831,140566,27426,8.26,126,13261,165,17.901530,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12
India,8,15005,14841,128763,37209,8.58,115,33195,26,14.969080,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12
France,9,13153,12973,130632,28601,9.93,114,10597,166,17.020280,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12
South Korea,10,11983,11923,114675,22595,9.57,104,11007,221,2.279353,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12
Italy,11,10964,10794,111850,26661,10.20,106,6530,109,33.667230,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12
Spain,12,9428,9330,123336,23964,13.08,115,4923,106,37.968590,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12
Iran,13,8896,8819,57470,19125,6.46,72,9172,119,5.707721,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN
Australia,14,8831,8725,90765,15606,10.28,107,5386,231,11.810810,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
Brazil,15,8668,8596,60702,14396,7.00,86,12149,59,69.648030,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12

In [169]:
df['% Renewable'].max()
#sort_values(ascending = False)
#df.index[0]
df.iloc[0,9]

19.75491

In [170]:
df_3=df.iloc[:,10:]
avgGDP = df_3.mean(axis=1).sort_values(ascending=False)
avgGDP

Country
United States         1.536434e+13
China                 6.348609e+12
Japan                 5.542208e+12
Germany               3.493025e+12
France                2.681725e+12
United Kingdom        2.487907e+12
Brazil                2.189794e+12
Italy                 2.120175e+12
India                 1.769297e+12
Canada                1.660647e+12
Russian Federation    1.565459e+12
Spain                 1.418078e+12
Australia             1.164043e+12
South Korea           1.106715e+12
Iran                  4.441558e+11
dtype: float64

In [119]:
#     num_outer = len(pd.concat([ScimEn['Country'],energy['Country'],GDP['Country']]).unique())
    
#     num_inter = (GDP.merge(energy, left_on='Country', right_on='Country', how='inner').merge(ScimEn, left_on='Country', right_on='Country', how='inner').shape[0])
    
#     print(num_outer-num_inter)

161

In [162]:
country=avgGDP.index[5]
df.loc[country]['2015']
#df.loc[country]['2015']

2666333396477.13

In [171]:
avgGDP.apply(lambda x:format(x,','))

Country
United States           15,364,344,302,990.0
China                    6,348,608,932,836.1
Japan                  5,542,207,638,235.176
Germany                3,493,025,339,072.848
France                 2,681,724,635,761.589
United Kingdom        2,487,906,661,418.4175
Brazil                2,189,794,143,774.9048
Italy                 2,120,175,089,933.7761
India                 1,769,297,396,603.8599
Canada                 1,660,647,466,307.512
Russian Federation     1,565,459,478,480.661
Spain                  1,418,078,278,145.694
Australia              1,164,042,729,991.427
South Korea            1,106,714,508,244.852
Iran                   444,155,754,051.09503
dtype: object